%% -*- mode: erlang;erlang-indent-level: 4;indent-tabs-mode: nil -*-
%% ex: ft=erlang ts=4 sw=4 et

WMDep = {deps, [{webmachine, "1.9.*", {git, "git://github.com/vinoski/webmachine", {branch, "yaws"}}}]}.

case os:getenv("WEBMACHINE_SERVER") of
    false ->
        %% default to mochiweb
        CONFIG;
    "mochiweb" ->
        CONFIG;
    "yaws" ->
        lists:keystore(deps, 1, CONFIG, WMDep)
end.
